<a href="https://colab.research.google.com/github/Jpmm28/FinCompJP/blob/main/Taller_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Taller 1 - Juan Pablo Moncada

Punto 1

In [56]:
import numpy as np
import pandas as pd
import pandas_datareader.data as pdr
import matplotlib.pyplot as plt
!pip install yfinance  --quiet yfinance
import yfinance as yf
from scipy import stats

In [57]:
yf.pdr_override()

In [58]:
activos=['KO','WMT']
data_source='Yahoo'
inicio='2021-01-01'
final='2022-12-28'
tabla=pdr.get_data_yahoo(activos,inicio,final)
tabla

[*********************100%***********************]  2 of 2 completed

            Adj Close                  Close                   High  \
                   KO         WMT         KO         WMT         KO
Date
2021-01-04  49.677780  142.004074  52.759998  146.529999  54.630001
2021-01-05  49.131664  141.248154  52.180000  145.750000  52.619999
2021-01-06  47.568634  142.130066  50.520000  146.660004  52.020000
2021-01-07  47.041359  142.120361  49.959999  146.649994  50.259998
2021-01-08  48.095924  142.100998  51.080002  146.630005  51.130001
...               ...         ...        ...         ...        ...
2022-12-20  62.790001  144.050003  62.790001  144.050003  63.150002
2022-12-21  63.799999  145.179993  63.799999  145.179993  64.050003
2022-12-22  63.340000  143.479996  63.340000  143.479996  63.590000
2022-12-23  63.820000  143.770004  63.820000  143.770004  63.869999
2022-12-27  64.209999  143.809998  64.209999  143.809998  64.290001

                              Low                   Open              \
                   WMT         KO         WMT         KO         WMT
Date
2021-01-04  146.889999  52.029999  144.279999  54.270000  144.300003
2021-01-05  147.070007  52.029999  144.490005  52.330002  146.600006
2021-01-06  148.100006  50.189999  145.009995  51.970001  145.089996
2021-01-07  147.759995  49.520000  146.039993  50.090000  147.619995
2021-01-08  147.000000  49.840000  145.809998  50.029999  146.880005
...                ...        ...         ...        ...         ...
2022-12-20  144.639999  62.750000  142.250000  62.820000  142.919998
2022-12-21  145.940002  63.070000  144.259995  63.070000  144.320007
2022-12-22  144.979996  62.650002  141.929993  63.419998  144.770004
2022-12-23  143.800003  63.200001  142.279999  63.500000  143.050003
2022-12-27  144.449997  63.709999  143.190002  63.930000  144.039993

              Volume
                  KO       WMT
Date
2021-01-04  25611100  10727400
2021-01-05  20323800   8832700
2021-01-06  38724500   7306300
2021-01-07  53225700   6846000
2021-01-08  29674000   8159400
...              ...       ...
2022-12-20  10286500   5669800
2022-12-21  10411300   4575500
2022-12-22   9666700   4360800
2022-12-23   6463300   3182500
2022-12-27   7320700   3348200

[500 rows x 12 columns]

In [59]:
retornosd = np.log(tabla/tabla.shift()).dropna()
retornosd

           Adj Close               Close                High            \
                  KO       WMT        KO       WMT        KO       WMT
Date
2021-01-05 -0.011054 -0.005337 -0.011054 -0.005337 -0.037487  0.001225
2021-01-06 -0.032330  0.006224 -0.032330  0.006224 -0.011468  0.006979
2021-01-07 -0.011146 -0.000068 -0.011147 -0.000068 -0.034419 -0.002298
2021-01-08  0.022170 -0.000136  0.022170 -0.000136  0.017162 -0.005157
2021-01-11 -0.017378  0.004491 -0.017378  0.004491 -0.005295  0.006712
...              ...       ...       ...       ...       ...       ...
2022-12-20 -0.000796  0.008715 -0.000796  0.008715 -0.004109  0.007495
2022-12-21  0.015957  0.007814  0.015957  0.007814  0.014151  0.008948
2022-12-22 -0.007236 -0.011779 -0.007236 -0.011779 -0.007208 -0.006600
2022-12-23  0.007550  0.002019  0.007550  0.002019  0.004394 -0.008172
2022-12-27  0.006092  0.000278  0.006092  0.000278  0.006554  0.004510

                 Low                Open              Volume
                  KO       WMT        KO       WMT        KO       WMT
Date
2021-01-05  0.000000  0.001454 -0.036402  0.015813 -0.231233 -0.194340
2021-01-06 -0.036005  0.003592 -0.006903 -0.010354  0.644680 -0.189724
2021-01-07 -0.013439  0.007078 -0.036845  0.017287  0.318069 -0.065072
2021-01-08  0.006441 -0.001576 -0.001199 -0.005025 -0.584270  0.175506
2021-01-11  0.002205  0.001302  0.011724 -0.006009 -0.429938  0.070431
...              ...       ...       ...       ...       ...       ...
2022-12-20  0.004472  0.003662 -0.000159 -0.000629 -0.059736  0.121226
2022-12-21  0.005087  0.014031  0.003972  0.009748  0.012059 -0.214438
2022-12-22 -0.006682 -0.016283  0.005534  0.003113 -0.074205 -0.048060
2022-12-23  0.008741  0.002463  0.001261 -0.011952 -0.402547 -0.314988
2022-12-27  0.008037  0.006375  0.006749  0.006897  0.124566  0.050756

[499 rows x 12 columns]

In [60]:
retornosm=retornosd*20
retornosm

           Adj Close               Close                High            \
                  KO       WMT        KO       WMT        KO       WMT
Date
2021-01-05 -0.221081 -0.106749 -0.221080 -0.106747 -0.749739  0.024494
2021-01-06 -0.646603  0.124486 -0.646600  0.124484 -0.229360  0.139581
2021-01-07 -0.222928 -0.001366 -0.222933 -0.001365 -0.688375 -0.045969
2021-01-08  0.443405 -0.002725  0.443408 -0.002726  0.343239 -0.103134
2021-01-11 -0.347560  0.089819 -0.347561  0.089819 -0.105893  0.134243
...              ...       ...       ...       ...       ...       ...
2022-12-20 -0.015920  0.174308 -0.015920  0.174308 -0.082174  0.149897
2022-12-21  0.319147  0.156276  0.319147  0.156276  0.283024  0.178954
2022-12-22 -0.144723 -0.235574 -0.144723 -0.235574 -0.144157 -0.131996
2022-12-23  0.150991  0.040384  0.150991  0.040384  0.087870 -0.163446
2022-12-27  0.121847  0.005563  0.121847  0.005563  0.131087  0.090199

                 Low                Open               Volume
                  KO       WMT        KO       WMT         KO       WMT
Date
2021-01-05  0.000000  0.029090 -0.728035  0.316267  -4.624665 -3.886809
2021-01-06 -0.720094  0.071847 -0.138064 -0.207072  12.893597 -3.794475
2021-01-07 -0.268783  0.141557 -0.736905  0.345743   6.361378 -1.301449
2021-01-08  0.128825 -0.031522 -0.023972 -0.100508 -11.685402  3.510122
2021-01-11  0.044093  0.026045  0.234479 -0.120187  -8.598764  1.408630
...              ...       ...       ...       ...        ...       ...
2022-12-20  0.089442  0.073245 -0.003184 -0.012590  -1.194723  2.424521
2022-12-21  0.101733  0.280622  0.079435  0.194962   0.241188 -4.288757
2022-12-22 -0.133630 -0.325665  0.110680  0.062264  -1.484095 -0.961209
2022-12-23  0.174812  0.049260  0.025213 -0.239041  -8.050939 -6.299770
2022-12-27  0.160744  0.127510  0.134977  0.137935   2.491319  1.015117

[499 rows x 12 columns]

In [61]:
retornosa=retornosd*252
retornosa

           Adj Close               Close                High            \
                  KO       WMT        KO       WMT        KO       WMT
Date
2021-01-05 -2.785616 -1.345037 -2.785611 -1.345013 -9.446711  0.308627
2021-01-06 -8.147192  1.568523 -8.147155  1.568494 -2.889933  1.758720
2021-01-07 -2.808894 -0.017207 -2.808953 -0.017200 -8.673530 -0.579213
2021-01-08  5.586903 -0.034336  5.586941 -0.034351  4.324807 -1.299491
2021-01-11 -4.379255  1.131718 -4.379262  1.131719 -1.334254  1.691463
...              ...       ...       ...       ...       ...       ...
2022-12-20 -0.200586  2.196284 -0.200586  2.196284 -1.035393  1.888700
2022-12-21  4.021249  1.969082  4.021249  1.969082  3.566103  2.254821
2022-12-22 -1.823506 -2.968227 -1.823506 -2.968227 -1.816378 -1.663155
2022-12-23  1.902492  0.508840  1.902492  0.508840  1.107168 -2.059421
2022-12-27  1.535268  0.070090  1.535268  0.070090  1.651699  1.136505

                 Low                Open                Volume
                  KO       WMT        KO       WMT          KO        WMT
Date
2021-01-05  0.000000  0.366532 -9.173239  3.984963  -58.270776 -48.973799
2021-01-06 -9.073178  0.905267 -1.739607 -2.609111  162.459325 -47.810386
2021-01-07 -3.386663  1.783616 -9.285006  4.356364   80.153360 -16.398257
2021-01-08  1.623192 -0.397183 -0.302045 -1.266404 -147.236070  44.227536
2021-01-11  0.555570  0.328163  2.954431 -1.514353 -108.344424  17.748734
...              ...       ...       ...       ...         ...        ...
2022-12-20  1.126973  0.922891 -0.040120 -0.158634  -15.053508  30.548959
2022-12-21  1.281833  3.535841  1.000875  2.456518    3.038969 -54.038341
2022-12-22 -1.683741 -4.103382  1.394574  0.784526  -18.699601 -12.111235
2022-12-23  2.202633  0.620679  0.317688 -3.011920 -101.441836 -79.377096
2022-12-27  2.025377  1.606626  1.700706  1.737981   31.390614  12.790471

[499 rows x 12 columns]

B.

In [62]:
volatilidadm=retornosm.std()
volatilidadm

Adj Close  KO     0.219977
           WMT    0.283847
Close      KO     0.221876
           WMT    0.283905
High       KO     0.199552
           WMT    0.245717
Low        KO     0.205548
           WMT    0.261912
Open       KO     0.224010
           WMT    0.274699
Volume     KO     6.360940
           WMT    7.231110
dtype: float64

In [63]:
volatilidadm*12

Adj Close  KO      2.639720
           WMT     3.406163
Close      KO      2.662511
           WMT     3.406861
High       KO      2.394622
           WMT     2.948608
Low        KO      2.466575
           WMT     3.142941
Open       KO      2.688125
           WMT     3.296389
Volume     KO     76.331282
           WMT    86.773319
dtype: float64

C.

In [64]:
retornosd.describe()

        Adj Close                   Close                    High              \
               KO         WMT          KO         WMT          KO         WMT
count  499.000000  499.000000  499.000000  499.000000  499.000000  499.000000
mean     0.000514    0.000025    0.000394   -0.000038    0.000326   -0.000034
std      0.010999    0.014192    0.011094    0.014195    0.009978    0.012286
min     -0.072168   -0.120765   -0.072169   -0.120765   -0.072137   -0.085646
25%     -0.004927   -0.006438   -0.005153   -0.006438   -0.004684   -0.006265
50%      0.001129    0.000501    0.001129    0.000404    0.000000    0.000491
75%      0.006814    0.007757    0.006814    0.007655    0.005558    0.005780
max      0.037942    0.063346    0.037942    0.063346    0.036921    0.053638

              Low                    Open                  Volume
               KO         WMT          KO         WMT          KO         WMT
count  499.000000  499.000000  499.000000  499.000000  499.000000  499.000000
mean     0.000406   -0.000015    0.000328   -0.000004   -0.002510   -0.002333
std      0.010277    0.013096    0.011201    0.013735    0.318047    0.361555
min     -0.064323   -0.114307   -0.070610   -0.090682   -1.331799   -1.069852
25%     -0.004773   -0.005758   -0.005366   -0.006781   -0.174409   -0.216605
50%      0.001179    0.000830    0.000636    0.000000   -0.013880   -0.019601
75%      0.006241    0.006767    0.006750    0.007156    0.172233    0.175728
max      0.033744    0.050688    0.041500    0.053759    1.326459    1.824217

In [65]:
retornosd.kurtosis()

Adj Close  KO      4.402020
           WMT    14.427318
Close      KO      4.426783
           WMT    14.383929
High       KO      6.517005
           WMT    10.921747
Low        KO      4.313293
           WMT    17.995999
Open       KO      3.951003
           WMT     8.542520
Volume     KO      2.570465
           WMT     3.003264
dtype: float64

In [66]:
retornosd.skew()

Adj Close  KO    -0.709275
           WMT   -1.749512
Close      KO    -0.772245
           WMT   -1.740133
High       KO    -0.709371
           WMT   -1.333574
Low        KO    -0.776519
           WMT   -2.252318
Open       KO    -0.571493
           WMT   -1.278680
Volume     KO     0.115177
           WMT    0.732053
dtype: float64

D.

In [71]:
from scipy.stats import norm
x = np.linspace(-0.1,0.1, num=100)
plt.hist(retornosd['WMT'],bins=20,density=True, histtype='step');
plt.plot(x,norm.pdf(x,scale=retornosd['WMT'].std()),'k')
plt.axvline((retornosd['WMT'].mean()), color='r');
plt.xlabel('Retornos');
plt.ylabel('Probabilidad');

KeyError: ignored

In [69]:
from scipy.stats import norm
x = np.linspace(-0.1,0.1, num=100)
plt.hist(retornosd['KO'],bins=20,density=True, histtype='step');
plt.plot(x,norm.pdf(x,scale=retornosd['KO'].std()),'k')
plt.axvline((retornosd['KO'].mean()), color='r');
plt.xlabel('Retornos');
plt.ylabel('Probabilidad');

KeyError: ignored

E.

In [ ]:
retornosd['NVDA'].corr(retornosd['KO'],method="pearson")

In [ ]:
retornosd['NVDA'].corr(retornosd['KO'],method="kendall")

In [ ]:
retornosd['NVDA'].corr(retornosd['KO'],method="spearman")

Punto 2

In [72]:
activos=['V','JPM','JNJ','DHR','CVS','XOM','TSLA','VZ','TGT','PEP']
fuente='yahoo'
inicio='2017-12-01'
final='2022-12-28'
tabla2=data.DataReader(activos,inicio,final,interval='1Mo')['Adj Close']
tabla2

[*********************100%***********************]  10 of 10 completed

,CVS,DHR,JNJ,JPM,PEP,TGT,TSLA,V,VZ,XOM
Date,,,,,,,,,,
2017-12-01,62.563751,90.648186,122.416870,91.832275,103.647469,57.940540,20.756666,110.121429,41.475784,64.310326
2018-01-01,67.905396,99.058479,121.076363,99.328941,103.975937,66.793694,23.620667,119.982346,42.369083,67.124496
2018-02-01,58.810738,95.635246,113.795479,99.699631,94.840240,66.962402,22.870667,118.736450,37.835011,58.236057
2018-03-01,54.017670,95.762390,112.998695,94.926155,94.338936,62.161404,17.742001,115.731087,37.898399,57.953842
2018-04-01,60.634193,98.281235,111.534943,93.898933,87.887749,64.999550,19.593332,122.755066,39.110966,60.392838
...,...,...,...,...,...,...,...,...,...,...
2022-08-01,96.891846,269.396606,159.235397,111.894966,170.059219,158.348038,275.609985,197.529419,40.480667,93.914124
2022-09-01,94.147476,257.798737,162.312347,102.813889,161.164825,147.465027,265.250000,176.907303,36.762756,86.612747
2022-10-01,93.486061,251.427399,172.854309,123.848915,180.454361,163.226166,227.539993,206.293945,36.181831,109.925072
2022-11-01,101.181160,273.146454,176.858459,137.166794,184.360001,166.028595,194.699997,216.092804,38.376682,110.450844
2022-12-01,92.550774,265.164154,176.649994,133.116730,179.540070,149.039993,123.180000,207.353867,38.790184,110.300003

a.

In [73]:
retornosp=np.log(tabla2/tabla2.shift()).dropna()
retornosp

,CVS,DHR,JNJ,JPM,PEP,TGT,TSLA,V,VZ,XOM
Date,,,,,,,,,,
2018-01-01,0.081929,0.088724,-0.011011,0.078473,0.003164,0.142191,0.129255,0.085761,0.021309,0.042829
2018-02-01,-0.143791,-0.035169,-0.062019,0.003725,-0.091966,0.002523,-0.032267,-0.010438,-0.113184,-0.142044
2018-03-01,-0.085013,0.001329,-0.007027,-0.049063,-0.005300,-0.074397,-0.253920,-0.025637,0.001674,-0.004858
2018-04-01,0.115548,0.025963,-0.013038,-0.010880,-0.070834,0.044646,0.099255,0.058922,0.031494,0.041224
2018-05-01,-0.089137,-0.010421,-0.055843,-0.011347,-0.006859,0.003986,-0.031698,0.029816,-0.022131,0.043909
2018-06-01,0.015031,-0.006062,0.021666,-0.026610,0.091642,0.051901,0.186043,0.014753,0.053901,0.028260
2018-07-01,0.007894,0.040392,0.088137,0.098185,0.054778,0.058180,-0.140021,0.031876,0.026093,-0.014857
2018-08-01,0.156017,0.009315,0.016242,0.002195,-0.026344,0.081148,0.011737,0.071603,0.063043,-0.016576
2018-09-01,0.045215,0.048266,0.032151,-0.015302,-0.001877,0.015911,-0.130439,0.023053,-0.018189,0.068999
2018-10-01,-0.083829,-0.087601,0.013086,-0.034440,0.013412,-0.053318,0.242171,-0.085069,0.067005,-0.064868
2018-11-01,0.109343,0.097138,0.048181,0.026688,0.081643,-0.164286,0.038272,0.027616,0.065723,-0.002261
2018-12-01,-0.202168,-0.060396,-0.123204,-0.130158,-0.098695,-0.062838,-0.051762,-0.069642,-0.070059,-0.143373
2019-01-01,0.000458,0.074517,0.030750,0.058489,0.027538,0.099442,-0.080629,0.023001,-0.020849,0.071990
2019-02-01,-0.117714,0.135536,0.026399,0.016363,0.026019,-0.004944,0.041033,0.092674,0.043606,0.075540
2019-03-01,-0.069821,0.038609,0.029402,-0.030451,0.066113,0.108581,-0.133656,0.054794,0.038092,0.033191
2019-04-01,0.008310,0.004487,0.010036,0.136626,0.043902,-0.036026,-0.159124,0.051412,-0.033359,-0.006456
2019-05-01,-0.028117,-0.003252,-0.073836,-0.083337,-0.000391,0.038391,-0.253945,-0.019033,-0.040684,-0.126085
2019-06-01,0.039683,0.079408,0.066964,0.053650,0.024159,0.082748,0.188012,0.074551,0.049885,0.090951
2019-07-01,0.025010,-0.015871,-0.067261,0.036879,-0.018349,-0.002428,0.078092,0.025318,-0.033099,-0.030070
2019-08-01,0.095459,0.011253,-0.014387,-0.047328,0.067463,0.214215,-0.068517,0.015718,0.061438,-0.082377
2019-09-01,0.034684,0.016334,0.015380,0.068847,0.002703,0.006437,0.065450,-0.048508,0.037129,0.042987
2019-10-01,0.051301,-0.045664,0.020351,0.059619,0.007397,0.000000,0.268061,0.039051,0.001821,-0.044008
2019-11-01,0.133075,0.057521,0.040446,0.061287,-0.009817,0.156406,0.046592,0.031100,0.006541,0.008254
2019-12-01,-0.013105,0.050100,0.066069,0.056365,0.006165,0.031188,0.237360,0.019880,0.019073,0.035917
2020-01-01,-0.091119,0.048136,0.020358,-0.051822,0.045379,-0.146484,0.441578,0.057244,-0.032442,-0.116279
2020-02-01,-0.129548,-0.106763,-0.101658,-0.124588,-0.072939,-0.072456,0.026424,-0.090467,-0.082672,-0.188652
2020-03-01,0.002531,-0.043613,-0.018870,-0.254395,-0.094705,-0.096777,-0.242781,-0.119091,-0.007971,-0.289365
2020-04-01,0.036735,0.167741,0.134712,0.061702,0.103401,0.165837,0.400210,0.103671,0.066944,0.202010
2020-05-01,0.071602,0.019087,-0.008635,0.026394,-0.005609,0.108608,0.065730,0.088409,0.009478,-0.021754
2020-06-01,-0.009193,0.059533,-0.049226,-0.033969,0.005383,-0.014529,0.257109,-0.008986,-0.040002,0.002572
2020-07-01,-0.031744,0.143001,0.035829,0.027060,0.047749,0.048421,0.281421,-0.014444,0.041743,-0.060848
2020-08-01,-0.005334,0.013016,0.051153,0.045773,0.017284,0.183341,0.554719,0.107412,0.041834,-0.052194
2020-09-01,-0.061752,0.042017,-0.023340,-0.039912,-0.010479,0.045179,-0.149762,-0.056861,0.003705,-0.131823
2020-10-01,-0.040358,0.064790,-0.082357,0.018219,-0.031900,-0.033590,-0.100372,-0.095755,-0.042932,-0.051094
2020-11-01,0.197906,-0.021623,0.053741,0.193528,0.078882,0.165015,0.380309,0.146361,0.068870,0.156076
2020-12-01,0.007495,-0.011147,0.091064,0.075071,0.027828,-0.012726,0.217731,0.040571,-0.027863,0.101762
2021-01-01,0.047883,0.069107,0.035884,0.012513,-0.075301,0.025945,0.117344,-0.123853,-0.070514,0.084177
2021-02-01,-0.043709,-0.079472,-0.029045,0.141513,-0.055553,0.012452,-0.161038,0.094439,0.020644,0.192712
2021-03-01,0.099133,0.024330,0.042712,0.033804,0.090662,0.080291,-0.011270,-0.001561,0.050253,0.043339
2021-04-01,0.015433,0.121599,-0.009906,0.010326,0.026931,0.045354,0.060293,0.098127,-0.006210,0.024942
2021-05-01,0.130008,0.008626,0.039285,0.071483,0.025883,0.090624,-0.126372,-0.027168,-0.012051,0.019549
2021-06-01,-0.035323,0.046605,-0.020789,-0.054426,0.001554,0.066508,0.083548,0.029732,-0.008176,0.092065
2021-07-01,-0.013028,0.103833,0.044288,-0.024471,0.064846,0.076849,0.010974,0.052364,-0.004472,-0.091402
2021-08-01,0.053810,0.085857,0.005386,0.058175,-0.003575,-0.055405,0.068224,-0.072757,-0.002911,-0.054434
2021-09-01,-0.017869,-0.062763,-0.063613,0.023113,-0.038988,-0.073164,0.052633,-0.026746,-0.018164,0.090937
2021-10-01,0.050775,0.024483,0.008509,0.037177,0.078590,0.126502,0.362230,-0.050549,-0.019066,0.091718
2021-11-01,0.003327,0.031167,-0.043606,-0.061309,-0.011326,-0.062707,0.027238,-0.088829,-0.040889,-0.074526
2021-12-01,0.146971,0.022655,0.099194,-0.003027,0.083589,-0.048781,-0.079968,0.113647,0.033066,0.035659
2022-01-01,0.031958,-0.140181,0.007106,-0.063550,0.005640,-0.048740,-0.120597,0.042727,0.024148,0.216223
2022-02-01,-0.021888,-0.040634,-0.045843,-0.040864,-0.058013,-0.098413,-0.073397,-0.045453,0.020208,0.031872
2022-03-01,-0.023822,0.066675,0.080511,-0.039413,0.021987,0.064781,0.213504,0.027433,-0.052206,0.062835
2022-04-01,-0.051496,-0.154453,0.018061,-0.132861,0.032096,0.074569,-0.213125,-0.039739,-0.095507,0.031700
2022-05-01,0.011600,0.049296,-0.005167,0.109784,-0.023332,-0.345337,-0.138340,-0.004514,0.114457,0.118760
2022-06-01,-0.043193,-0.039824,-0.004910,-0.160612,-0.006519,-0.132352,-0.118657,-0.072835,-0.010584,-0.104005
2022-07-01,0.032072,0.140512,-0.016988,0.024127,0.055533,0.145689,0.280480,0.074460,-0.094148,0.123837
2022-08-01,0.031285,-0.076849,-0.078525,-0.005424,-0.015494,-0.018782,-0.075250,-0.065259,-0.087125,-0.013921
2022-09-01,-0.028733,-0.044005,0.019139,-0.084640,-0.053719,-0.071204,-0.038314,-0.110262,-0.096339,-0.080934
2022-10-01,-0.007050,-0.025025,0.062927,0.186142,0.113050,0.101546,-0.153347,0.153676,-0.015928,0.238352
2022-11-01,0.079100,0.082854,0.022901,0.102135,0.021412,0.017023,-0.155866,0.046406,0.058893,0.004772
2022-12-01,-0.089155,-0.029659,-0.001179,-0.029971,-0.026492,-0.107945,-0.457813,-0.041281,0.010717,-0.001367

In [74]:
retornosp*12

,CVS,DHR,JNJ,JPM,PEP,TGT,TSLA,V,VZ,XOM
Date,,,,,,,,,,
2018-01-01,0.983153,1.064693,-0.132129,0.941678,0.037969,1.706296,1.551055,1.029131,0.255710,0.513946
2018-02-01,-1.725493,-0.422027,-0.744224,0.044700,-1.103588,0.030272,-0.387203,-0.125259,-1.358209,-1.704532
2018-03-01,-1.020159,0.015943,-0.084318,-0.588752,-0.063598,-0.892764,-3.047045,-0.307645,0.020088,-0.058294
2018-04-01,1.386573,0.311557,-0.156460,-0.130563,-0.850003,0.535753,1.191055,0.707061,0.377928,0.494684
2018-05-01,-1.069640,-0.125052,-0.670117,-0.136164,-0.082310,0.047836,-0.380378,0.357791,-0.265576,0.526911
2018-06-01,0.180369,-0.072742,0.259988,-0.319322,1.099709,0.622810,2.232519,0.177035,0.646818,0.339115
2018-07-01,0.094730,0.484705,1.057645,1.178224,0.657332,0.698155,-1.680258,0.382516,0.313114,-0.178278
2018-08-01,1.872209,0.111782,0.194905,0.026346,-0.316126,0.973781,0.140849,0.859231,0.756515,-0.198918
2018-09-01,0.542575,0.579187,0.385814,-0.183628,-0.022522,0.190932,-1.565268,0.276638,-0.218270,0.827988
2018-10-01,-1.005954,-1.051215,0.157038,-0.413276,0.160943,-0.639815,2.906047,-1.020824,0.804065,-0.778418
2018-11-01,1.312121,1.165653,0.578168,0.320252,0.979718,-1.971433,0.459259,0.331397,0.788680,-0.027137
2018-12-01,-2.426017,-0.724756,-1.478448,-1.561897,-1.184335,-0.754051,-0.621143,-0.835700,-0.840713,-1.720474
2019-01-01,0.005496,0.894209,0.369005,0.701870,0.330452,1.193303,-0.967545,0.276016,-0.250192,0.863876
2019-02-01,-1.412564,1.626428,0.316793,0.196357,0.312223,-0.059325,0.492396,1.112091,0.523273,0.906476
2019-03-01,-0.837849,0.463307,0.352821,-0.365416,0.793362,1.302971,-1.603877,0.657530,0.457099,0.398286
2019-04-01,0.099715,0.053847,0.120435,1.639512,0.526821,-0.432315,-1.909486,0.616941,-0.400313,-0.077478
2019-05-01,-0.337404,-0.039027,-0.886027,-1.000040,-0.004688,0.460689,-3.047344,-0.228396,-0.488211,-1.513023
2019-06-01,0.476200,0.952891,0.803562,0.643797,0.289907,0.992978,2.256145,0.894608,0.598618,1.091407
2019-07-01,0.300122,-0.190446,-0.807131,0.442545,-0.220192,-0.029131,0.937108,0.303815,-0.397188,-0.360844
2019-08-01,1.145512,0.135041,-0.172640,-0.567941,0.809559,2.570578,-0.822203,0.188621,0.737261,-0.988518
2019-09-01,0.416204,0.196007,0.184565,0.826165,0.032431,0.077244,0.785395,-0.582091,0.445545,0.515849
2019-10-01,0.615617,-0.547973,0.244213,0.715434,0.088765,0.000000,3.216735,0.468610,0.021848,-0.528094
2019-11-01,1.596905,0.690254,0.485354,0.735448,-0.117802,1.876876,0.559106,0.373204,0.078488,0.099042
2019-12-01,-0.157263,0.601206,0.792829,0.676383,0.073980,0.374259,2.848317,0.238556,0.228878,0.431009
2020-01-01,-1.093430,0.577628,0.244292,-0.621864,0.544543,-1.757813,5.298940,0.686929,-0.389307,-1.395351
2020-02-01,-1.554571,-1.281160,-1.219895,-1.495056,-0.875263,-0.869472,0.317091,-1.085602,-0.992059,-2.263824
2020-03-01,0.030377,-0.523358,-0.226439,-3.052740,-1.136456,-1.161326,-2.913377,-1.429086,-0.095655,-3.472384
2020-04-01,0.440816,2.012891,1.616550,0.740427,1.240815,1.990043,4.802514,1.244053,0.803324,2.424125
2020-05-01,0.859222,0.229050,-0.103616,0.316733,-0.067311,1.303302,0.788766,1.060910,0.113736,-0.261047
2020-06-01,-0.110311,0.714400,-0.590718,-0.407627,0.064592,-0.174343,3.085304,-0.107831,-0.480024,0.030861
2020-07-01,-0.380926,1.716008,0.429949,0.324717,0.572990,0.581050,3.377048,-0.173323,0.500917,-0.730179
2020-08-01,-0.064008,0.156190,0.613831,0.549276,0.207409,2.200086,6.656632,1.288945,0.502003,-0.626330
2020-09-01,-0.741026,0.504199,-0.280075,-0.478940,-0.125746,0.542148,-1.797148,-0.682335,0.044460,-1.581875
2020-10-01,-0.484301,0.777478,-0.988290,0.218628,-0.382802,-0.403085,-1.204461,-1.149064,-0.515190,-0.613128
2020-11-01,2.374873,-0.259474,0.644893,2.322335,0.946586,1.980185,4.563702,1.756331,0.826437,1.872909
2020-12-01,0.089943,-0.133760,1.092764,0.900853,0.333937,-0.152717,2.612769,0.486850,-0.334362,1.221146
2021-01-01,0.574598,0.829280,0.430611,0.150154,-0.903611,0.311340,1.408124,-1.486240,-0.846166,1.010126
2021-02-01,-0.524506,-0.953660,-0.348544,1.698159,-0.666641,0.149422,-1.932458,1.133274,0.247729,2.312542
2021-03-01,1.189591,0.291954,0.512550,0.405651,1.087947,0.963498,-0.135238,-0.018732,0.603036,0.520063
2021-04-01,0.185190,1.459192,-0.118873,0.123908,0.323167,0.544243,0.723511,1.177524,-0.074523,0.299300
2021-05-01,1.560098,0.103515,0.471414,0.857796,0.310596,1.087482,-1.516468,-0.326018,-0.144611,0.234589
2021-06-01,-0.423873,0.559259,-0.249464,-0.653110,0.018642,0.798099,1.002575,0.356788,-0.098117,1.104774
2021-07-01,-0.156338,1.246000,0.531456,-0.293648,0.778155,0.922189,0.131686,0.628369,-0.053664,-1.096826
2021-08-01,0.645722,1.030281,0.064635,0.698100,-0.042895,-0.664854,0.818691,-0.873085,-0.034929,-0.653208
2021-09-01,-0.214429,-0.753160,-0.763355,0.277360,-0.467856,-0.877971,0.631591,-0.320954,-0.217967,1.091239
2021-10-01,0.609295,0.293795,0.102103,0.446122,0.943083,1.518023,4.346762,-0.606590,-0.228791,1.100617
2021-11-01,0.039918,0.374005,-0.523278,-0.735708,-0.135916,-0.752481,0.326854,-1.065947,-0.490665,-0.894307
2021-12-01,1.763652,0.271864,1.190333,-0.036319,1.003073,-0.585371,-0.959621,1.363763,0.396789,0.427908
2022-01-01,0.383492,-1.682177,0.085275,-0.762595,0.067682,-0.584886,-1.447170,0.512722,0.289775,2.594679
2022-02-01,-0.262660,-0.487606,-0.550117,-0.490372,-0.696157,-1.180962,-0.880764,-0.545437,0.242499,0.382464
2022-03-01,-0.285868,0.800096,0.966130,-0.472951,0.263843,0.777374,2.562051,0.329192,-0.626469,0.754015
2022-04-01,-0.617955,-1.853436,0.216731,-1.594330,0.385152,0.894828,-2.557503,-0.476862,-1.146078,0.380395
2022-05-01,0.139199,0.591554,-0.062001,1.317404,-0.279986,-4.144046,-1.660081,-0.054173,1.373483,1.425121
2022-06-01,-0.518321,-0.477891,-0.058921,-1.927348,-0.078228,-1.588227,-1.423886,-0.874016,-0.127010,-1.248055
2022-07-01,0.384868,1.686139,-0.203851,0.289527,0.666396,1.748269,3.365762,0.893519,-1.129780,1.486039
2022-08-01,0.375417,-0.922183,-0.942305,-0.065085,-0.185933,-0.225387,-0.903003,-0.783102,-1.045502,-0.167051
2022-09-01,-0.344795,-0.528066,0.229667,-1.015682,-0.644629,-0.854452,-0.459768,-1.323140,-1.156071,-0.971205
2022-10-01,-0.084601,-0.300299,0.755119,2.233703,1.356604,1.218549,-1.840161,1.844114,-0.191138,2.860224
2022-11-01,0.949203,0.994246,0.274808,1.225623,0.256950,0.204279,-1.870393,0.556871,0.706715,0.057259
2022-12-01,-1.069862,-0.355908,-0.014153,-0.359655,-0.317904,-1.295344,-5.493758,-0.495374,0.128606,-0.016399

In [75]:
volatilidad=retornosp.std()
volatilidad

CVS     0.077422
DHR     0.068040
JNJ     0.051181
JPM     0.080254
PEP     0.050668
TGT     0.098333
TSLA    0.196036
V       0.067957
VZ      0.049448
XOM     0.099396
dtype: float64

In [76]:
volatilidad*12

CVS     0.929070
DHR     0.816480
JNJ     0.614178
JPM     0.963047
PEP     0.608019
TGT     1.179992
TSLA    2.352436
V       0.815485
VZ      0.593378
XOM     1.192753
dtype: float64

b.

In [77]:
Er=retornosp.mean()
ranking=pd.DataFrame(Er)
ranking.index.name='Retorno Esperado'
ranking.sort_values(by=0, ascending=False)

                         0
Retorno Esperado
TSLA              0.029680
DHR               0.017889
TGT               0.015747
V                 0.010547
PEP               0.009157
XOM               0.008991
CVS               0.006526
JPM               0.006188
JNJ               0.006112
VZ               -0.001116

Punto 3

In [78]:
activos=['^RUT']
fuente='yahoo'
inicio='2011-12-01'
final='2022-12-28'
tabla3=data.DataReader(activos,inicio,final,interval='1Mo')['Adj Close']
tabla3

[*********************100%***********************]  1 of 1 completed

Date
2011-12-01     740.919983
2012-01-01     792.820007
2012-02-01     810.940002
2012-03-01     830.299988
2012-04-01     816.880005
                 ...
2022-08-01    1844.119995
2022-09-01    1664.719971
2022-10-01    1846.859985
2022-11-01    1886.579956
2022-12-01    1761.250000
Name: Adj Close, Length: 133, dtype: float64

a.

In [79]:
retornosr=np.log(tabla3/tabla3.shift()).dropna().loc[:]
r_mensuales=retornosr.std()
r_mensuales

0.05474479591479422

In [80]:
r_mensuales*12

0.6569375509775306

b.

In [81]:
activos=['^RUT']
fuente='yahoo'
inicio='2011-12-01'
final='2022-12-28'
tablaprecios=data.DataReader(activos,inicio,final,interval='1Mo')
tablaprecios

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2011-12-01,734.510010,753.190002,705.780029,740.919983,740.919983,75366190000
2012-01-01,750.700012,800.219971,736.780029,792.820007,792.820007,79567560000
2012-02-01,796.989990,833.020020,796.989990,810.940002,810.940002,78385710000
2012-03-01,813.969971,847.919983,785.409973,830.299988,830.299988,83899660000
2012-04-01,828.890015,841.059998,783.559998,816.880005,816.880005,74761710000
...,...,...,...,...,...,...
2022-08-01,1870.489990,2030.050049,1843.079956,1844.119995,1844.119995,92252350000
2022-09-01,1826.750000,1906.089966,1650.709961,1664.719971,1664.719971,94241020000
2022-10-01,1687.280029,1854.569946,1641.939941,1846.859985,1846.859985,95823760000
2022-11-01,1864.949951,1905.839966,1757.449951,1886.579956,1886.579956,92671910000
2022-12-01,1891.979980,1898.449951,1722.020020,1761.250000,1761.250000,85249330000

In [82]:
retornoslh = np.log(tablaprecios["High"]/tablaprecios["Low"]).dropna()
sigma1=((1/(4*np.log(2)))*retornoslh**2)**0.5
sigma1.mean()

0.05101216195814947

In [83]:
(sigma1.mean())*np.sqrt(252)

0.8097929662860792

C.

In [87]:
retnornosLH = np.log(tablaprecios["High"]/tablaprecios["Low"]).dropna()
retornosCO = np.log(tablaprecios["Close"]/tablaprecios["Open"]).dropna()
sigma2 = (0.5*retnornosLH**2-(2*np.log(2)-1)*retornosCO**2)**0.5
sigma2.mean()

0.05239855062447297

In [88]:
(sigma2.mean())*np.sqrt(252)

0.8318012040755021

d.

In [89]:
retornosE = np.log(tabla3/tabla3.shift()).dropna();
Lambda = 0.94
t = (retornosE-1)
t1 = t[::-1] 
k = np.arange(502-1,-1,-1)
k.shape

(502,)

In [90]:
alpha = np.power(Lambda,k)
pd.Series(alpha)
alpha.shape
alpha

array([3.44393268e-14, 3.66375817e-14, 3.89761507e-14, 4.14639901e-14,
       4.41106278e-14, 4.69261998e-14, 4.99214892e-14, 5.31079672e-14,
       5.64978374e-14, 6.01040824e-14, 6.39405132e-14, 6.80218225e-14,
       7.23636410e-14, 7.69825968e-14, 8.18963796e-14, 8.71238080e-14,
       9.26849022e-14, 9.86009598e-14, 1.04894638e-13, 1.11590040e-13,
       1.18712809e-13, 1.26290222e-13, 1.34351300e-13, 1.42926915e-13,
       1.52049910e-13, 1.61755223e-13, 1.72080025e-13, 1.83063856e-13,
       1.94748783e-13, 2.07179556e-13, 2.20403784e-13, 2.34472110e-13,
       2.49438415e-13, 2.65360016e-13, 2.82297889e-13, 3.00316904e-13,
       3.19486068e-13, 3.39878795e-13, 3.61573187e-13, 3.84652326e-13,
       4.09204602e-13, 4.35324045e-13, 4.63110686e-13, 4.92670943e-13,
       5.24118024e-13, 5.57572366e-13, 5.93162092e-13, 6.31023502e-13,
       6.71301597e-13, 7.14150636e-13, 7.59734719e-13, 8.08228424e-13,
       8.59817473e-13, 9.14699439e-13, 9.73084509e-13, 1.03519629e-12,
       1.10127265e-12, 1.17156664e-12, 1.24634749e-12, 1.32590159e-12,
       1.41053361e-12, 1.50056767e-12, 1.59634858e-12, 1.69824317e-12,
       1.80664167e-12, 1.92195922e-12, 2.04463747e-12, 2.17514625e-12,
       2.31398537e-12, 2.46168656e-12, 2.61881549e-12, 2.78597393e-12,
       2.96380205e-12, 3.15298091e-12, 3.35423501e-12, 3.56833511e-12,
       3.79610118e-12, 4.03840551e-12, 4.29617608e-12, 4.57040008e-12,
       4.86212775e-12, 5.17247633e-12, 5.50263439e-12, 5.85386638e-12,
       6.22751742e-12, 6.62501853e-12, 7.04789206e-12, 7.49775751e-12,
       7.97633777e-12, 8.48546572e-12, 9.02709119e-12, 9.60328850e-12,
       1.02162644e-11, 1.08683663e-11, 1.15620918e-11, 1.23000977e-11,
       1.30852103e-11, 1.39204365e-11, 1.48089750e-11, 1.57542287e-11,
       1.67598178e-11, 1.78295934e-11, 1.89676526e-11, 2.01783538e-11,
       2.14663338e-11, 2.28365254e-11, 2.42941759e-11, 2.58448680e-11,
       2.74945404e-11, 2.92495111e-11, 3.11165012e-11, 3.31026608e-11,
       3.52155966e-11, 3.74634006e-11, 3.98546815e-11, 4.23985974e-11,
       4.51048908e-11, 4.79839264e-11, 5.10467302e-11, 5.43050321e-11,
       5.77713108e-11, 6.14588413e-11, 6.53817460e-11, 6.95550490e-11,
       7.39947329e-11, 7.87178010e-11, 8.37423415e-11, 8.90875973e-11,
       9.47740397e-11, 1.00823447e-10, 1.07258986e-10, 1.14105304e-10,
       1.21388621e-10, 1.29136831e-10, 1.37379607e-10, 1.46148519e-10,
       1.55477147e-10, 1.65401221e-10, 1.75958745e-10, 1.87190155e-10,
       1.99138462e-10, 2.11849428e-10, 2.25371732e-10, 2.39757162e-10,
       2.55060810e-10, 2.71341288e-10, 2.88660944e-10, 3.07086111e-10,
       3.26687352e-10, 3.47539736e-10, 3.69723124e-10, 3.93322472e-10,
       4.18428162e-10, 4.45136342e-10, 4.73549300e-10, 5.03775851e-10,
       5.35931757e-10, 5.70140167e-10, 6.06532092e-10, 6.45246907e-10,
       6.86432879e-10, 7.30247744e-10, 7.76859302e-10, 8.26446066e-10,
       8.79197943e-10, 9.35316960e-10, 9.95018043e-10, 1.05852983e-09,
       1.12609557e-09, 1.19797401e-09, 1.27444043e-09, 1.35578769e-09,
       1.44232733e-09, 1.53439078e-09, 1.63233062e-09, 1.73652193e-09,
       1.84736376e-09, 1.96528060e-09, 2.09072404e-09, 2.22417451e-09,
       2.36614310e-09, 2.51717351e-09, 2.67784415e-09, 2.84877038e-09,
       3.03060678e-09, 3.22404977e-09, 3.42984018e-09, 3.64876615e-09,
       3.88166612e-09, 4.12943204e-09, 4.39301281e-09, 4.67341788e-09,
       4.97172115e-09, 5.28906505e-09, 5.62666495e-09, 5.98581378e-09,
       6.36788700e-09, 6.77434787e-09, 7.20675305e-09, 7.66675857e-09,
       8.15612613e-09, 8.67672993e-09, 9.23056376e-09, 9.81974868e-09,
       1.04465411e-08, 1.11133416e-08, 1.18227039e-08, 1.25773445e-08,
       1.33801538e-08, 1.42342061e-08, 1.51427725e-08, 1.61093324e-08,
       1.71375877e-08, 1.82314763e-08, 1.93951875e-08, 2.06331782e-08,
       2.19501896e-08, 2.33512655e-08, 2.48417718e-08, 2.64274169e-08,
       2.81142732e-08, 2.99088013e-08, 3.18178738e-08, 3.38488019e-08,
       3.60093637e-08, 3.83078337e-08, 4.07530146e-08, 4.33542708e-08,
       4.61215647e-08, 4.90654944e-08, 5.21973344e-08, 5.55290792e-08,
       5.90734885e-08, 6.28441367e-08, 6.68554646e-08, 7.11228347e-08,
       7.56625901e-08, 8.04921171e-08, 8.56299118e-08, 9.10956509e-08,
       9.69102669e-08, 1.03096029e-07, 1.09676626e-07, 1.16677262e-07,
       1.24124747e-07, 1.32047603e-07, 1.40476173e-07, 1.49442737e-07,
       1.58981636e-07, 1.69129400e-07, 1.79924893e-07, 1.91409461e-07,
       2.03627086e-07, 2.16624560e-07, 2.30451659e-07, 2.45161339e-07,
       2.60809936e-07, 2.77457378e-07, 2.95167424e-07, 3.14007898e-07,
       3.34050955e-07, 3.55373356e-07, 3.78056762e-07, 4.02188045e-07,
       4.27859622e-07, 4.55169811e-07, 4.84223203e-07, 5.15131067e-07,
       5.48011773e-07, 5.82991248e-07, 6.20203455e-07, 6.59790910e-07,
       7.01905223e-07, 7.46707684e-07, 7.94369877e-07, 8.45074337e-07,
       8.99015252e-07, 9.56399205e-07, 1.01744596e-06, 1.08238932e-06,
       1.15147800e-06, 1.22497660e-06, 1.30316659e-06, 1.38634744e-06,
       1.47483770e-06, 1.56897628e-06, 1.66912370e-06, 1.77566351e-06,
       1.88900374e-06, 2.00957844e-06, 2.13784941e-06, 2.27430788e-06,
       2.41947647e-06, 2.57391114e-06, 2.73820334e-06, 2.91298227e-06,
       3.09891731e-06, 3.29672054e-06, 3.50714951e-06, 3.73101012e-06,
       3.96915970e-06, 4.22251032e-06, 4.49203226e-06, 4.77875772e-06,
       5.08378481e-06, 5.40828171e-06, 5.75349118e-06, 6.12073530e-06,
       6.51142053e-06, 6.92704312e-06, 7.36919481e-06, 7.83956895e-06,
       8.33996696e-06, 8.87230528e-06, 9.43862264e-06, 1.00410879e-05,
       1.06820084e-05, 1.13638387e-05, 1.20891902e-05, 1.28608406e-05,
       1.36817453e-05, 1.45550482e-05, 1.54840938e-05, 1.64724402e-05,
       1.75238726e-05, 1.86424177e-05, 1.98323592e-05, 2.10982545e-05,
       2.24449516e-05, 2.38776081e-05, 2.54017107e-05, 2.70230965e-05,
       2.87479750e-05, 3.05829521e-05, 3.25350554e-05, 3.46117611e-05,
       3.68210225e-05, 3.91713005e-05, 4.16715963e-05, 4.43314854e-05,
       4.71611547e-05, 5.01714411e-05, 5.33738735e-05, 5.67807165e-05,
       6.04050176e-05, 6.42606570e-05, 6.83624011e-05, 7.27259586e-05,
       7.73680411e-05, 8.23064267e-05, 8.75600284e-05, 9.31489663e-05,
       9.90946450e-05, 1.05419835e-04, 1.12148761e-04, 1.19307192e-04,
       1.26922545e-04, 1.35023984e-04, 1.43642536e-04, 1.52811209e-04,
       1.62565116e-04, 1.72941612e-04, 1.83980439e-04, 1.95723871e-04,
       2.08216884e-04, 2.21507324e-04, 2.35646089e-04, 2.50687329e-04,
       2.66688647e-04, 2.83711327e-04, 3.01820561e-04, 3.21085703e-04,
       3.41580535e-04, 3.63383548e-04, 3.86578242e-04, 4.11253449e-04,
       4.37503670e-04, 4.65429436e-04, 4.95137697e-04, 5.26742231e-04,
       5.60364076e-04, 5.96131996e-04, 6.34182974e-04, 6.74662738e-04,
       7.17726317e-04, 7.63538636e-04, 8.12275144e-04, 8.64122494e-04,
       9.19279249e-04, 9.77956648e-04, 1.04037941e-03, 1.10678661e-03,
       1.17743256e-03, 1.25258783e-03, 1.33254025e-03, 1.41759601e-03,
       1.50808086e-03, 1.60434134e-03, 1.70674611e-03, 1.81568735e-03,
       1.93158228e-03, 2.05487477e-03, 2.18603699e-03, 2.32557127e-03,
       2.47401198e-03, 2.63192764e-03, 2.79992303e-03, 2.97864152e-03,
       3.16876757e-03, 3.37102933e-03, 3.58620141e-03, 3.81510789e-03,
       4.05862541e-03, 4.31768661e-03, 4.59328363e-03, 4.88647194e-03,
       5.19837441e-03, 5.53018554e-03, 5.88317611e-03, 6.25869799e-03,
       6.65818935e-03, 7.08318016e-03, 7.53529804e-03, 8.01627451e-03,
       8.52795161e-03, 9.07228894e-03, 9.65137122e-03, 1.02674162e-02,
       1.09227832e-02, 1.16199821e-02, 1.23616831e-02, 1.31507267e-02,
       1.39901348e-02, 1.48831221e-02, 1.58331086e-02, 1.68437326e-02,
       1.79188644e-02, 1.90626217e-02, 2.02793848e-02, 2.15738137e-02,
       2.29508656e-02, 2.44158145e-02, 2.59742707e-02, 2.76322029e-02,
       2.93959605e-02, 3.12722984e-02, 3.32684026e-02, 3.53919176e-02,
       3.76509762e-02, 4.00542300e-02, 4.26108830e-02, 4.53307266e-02,
       4.82241772e-02, 5.13023162e-02, 5.45769321e-02, 5.80605661e-02,
       6.17665596e-02, 6.57091060e-02, 6.99033042e-02, 7.43652173e-02,
       7.91119333e-02, 8.41616311e-02, 8.95336502e-02, 9.52485640e-02,
       1.01328260e-01, 1.07796021e-01, 1.14676618e-01, 1.21996402e-01,
       1.29783406e-01, 1.38067454e-01, 1.46880270e-01, 1.56255606e-01,
       1.66229368e-01, 1.76839753e-01, 1.88127397e-01, 2.00135529e-01,
       2.12910137e-01, 2.26500146e-01, 2.40957602e-01, 2.56337875e-01,
       2.72699867e-01, 2.90106241e-01, 3.08623661e-01, 3.28323043e-01,
       3.49279833e-01, 3.71574291e-01, 3.95291799e-01, 4.20523190e-01,
       4.47365096e-01, 4.75920315e-01, 5.06298207e-01, 5.38615114e-01,
       5.72994802e-01, 6.09568939e-01, 6.48477594e-01, 6.89869781e-01,
       7.33904022e-01, 7.80748960e-01, 8.30584000e-01, 8.83600000e-01,
       9.40000000e-01, 1.00000000e+00])

In [91]:
EWMA = (alpha[370:502]*retornosE**2)
np.sqrt(EWMA)

Date
2012-01-01    0.001176
2012-02-01    0.000405
2012-03-01    0.000436
2012-04-01    0.000311
2012-05-01    0.001372
                ...
2022-08-01    0.019481
2022-09-01    0.093274
2022-10-01    0.097600
2022-11-01    0.020631
2022-12-01    0.068742
Name: Adj Close, Length: 132, dtype: float64

In [92]:
Anual=EWMA.sum()*(1-Lambda)
Anual

0.004665940526327016