<a href="https://colab.research.google.com/github/Jpmm28/FinCompJP/blob/main/Taller_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Taller 1 - Juan Pablo Moncada

Punto 1

In [56]:
import numpy as np
import pandas as pd
import pandas_datareader.data as pdr
import matplotlib.pyplot as plt
!pip install yfinance  --quiet yfinance
import yfinance as yf
from scipy import stats

In [57]:
yf.pdr_override()

In [58]:
activos=['KO','WMT']
data_source='Yahoo'
inicio='2021-01-01'
final='2022-12-28'
tabla=pdr.get_data_yahoo(activos,inicio,final)
tabla

[*********************100%***********************]  2 of 2 completed

            Adj Close                  Close                   High  \
                   KO         WMT         KO         WMT         KO
Date
2021-01-04  49.677780  142.004074  52.759998  146.529999  54.630001
2021-01-05  49.131664  141.248154  52.180000  145.750000  52.619999
2021-01-06  47.568634  142.130066  50.520000  146.660004  52.020000
2021-01-07  47.041359  142.120361  49.959999  146.649994  50.259998
2021-01-08  48.095924  142.100998  51.080002  146.630005  51.130001
...               ...         ...        ...         ...        ...
2022-12-20  62.790001  144.050003  62.790001  144.050003  63.150002
2022-12-21  63.799999  145.179993  63.799999  145.179993  64.050003
2022-12-22  63.340000  143.479996  63.340000  143.479996  63.590000
2022-12-23  63.820000  143.770004  63.820000  143.770004  63.869999
2022-12-27  64.209999  143.809998  64.209999  143.809998  64.290001

                              Low                   Open              \
                   WMT         KO         WMT         KO         WMT
Date
2021-01-04  146.889999  52.029999  144.279999  54.270000  144.300003
2021-01-05  147.070007  52.029999  144.490005  52.330002  146.600006
2021-01-06  148.100006  50.189999  145.009995  51.970001  145.089996
2021-01-07  147.759995  49.520000  146.039993  50.090000  147.619995
2021-01-08  147.000000  49.840000  145.809998  50.029999  146.880005
...                ...        ...         ...        ...         ...
2022-12-20  144.639999  62.750000  142.250000  62.820000  142.919998
2022-12-21  145.940002  63.070000  144.259995  63.070000  144.320007
2022-12-22  144.979996  62.650002  141.929993  63.419998  144.770004
2022-12-23  143.800003  63.200001  142.279999  63.500000  143.050003
2022-12-27  144.449997  63.709999  143.190002  63.930000  144.039993

              Volume
                  KO       WMT
Date
2021-01-04  25611100  10727400
2021-01-05  20323800   8832700
2021-01-06  38724500   7306300
2021-01-07  53225700   6846000
2021-01-08  29674000   8159400
...              ...       ...
2022-12-20  10286500   5669800
2022-12-21  10411300   4575500
2022-12-22   9666700   4360800
2022-12-23   6463300   3182500
2022-12-27   7320700   3348200

[500 rows x 12 columns]

In [59]:
retornosd = np.log(tabla/tabla.shift()).dropna()
retornosd

           Adj Close               Close                High            \
                  KO       WMT        KO       WMT        KO       WMT
Date
2021-01-05 -0.011054 -0.005337 -0.011054 -0.005337 -0.037487  0.001225
2021-01-06 -0.032330  0.006224 -0.032330  0.006224 -0.011468  0.006979
2021-01-07 -0.011146 -0.000068 -0.011147 -0.000068 -0.034419 -0.002298
2021-01-08  0.022170 -0.000136  0.022170 -0.000136  0.017162 -0.005157
2021-01-11 -0.017378  0.004491 -0.017378  0.004491 -0.005295  0.006712
...              ...       ...       ...       ...       ...       ...
2022-12-20 -0.000796  0.008715 -0.000796  0.008715 -0.004109  0.007495
2022-12-21  0.015957  0.007814  0.015957  0.007814  0.014151  0.008948
2022-12-22 -0.007236 -0.011779 -0.007236 -0.011779 -0.007208 -0.006600
2022-12-23  0.007550  0.002019  0.007550  0.002019  0.004394 -0.008172
2022-12-27  0.006092  0.000278  0.006092  0.000278  0.006554  0.004510

                 Low                Open              Volume
                  KO       WMT        KO       WMT        KO       WMT
Date
2021-01-05  0.000000  0.001454 -0.036402  0.015813 -0.231233 -0.194340
2021-01-06 -0.036005  0.003592 -0.006903 -0.010354  0.644680 -0.189724
2021-01-07 -0.013439  0.007078 -0.036845  0.017287  0.318069 -0.065072
2021-01-08  0.006441 -0.001576 -0.001199 -0.005025 -0.584270  0.175506
2021-01-11  0.002205  0.001302  0.011724 -0.006009 -0.429938  0.070431
...              ...       ...       ...       ...       ...       ...
2022-12-20  0.004472  0.003662 -0.000159 -0.000629 -0.059736  0.121226
2022-12-21  0.005087  0.014031  0.003972  0.009748  0.012059 -0.214438
2022-12-22 -0.006682 -0.016283  0.005534  0.003113 -0.074205 -0.048060
2022-12-23  0.008741  0.002463  0.001261 -0.011952 -0.402547 -0.314988
2022-12-27  0.008037  0.006375  0.006749  0.006897  0.124566  0.050756

[499 rows x 12 columns]

In [60]:
retornosm=retornosd*20
retornosm

           Adj Close               Close                High            \
                  KO       WMT        KO       WMT        KO       WMT
Date
2021-01-05 -0.221081 -0.106749 -0.221080 -0.106747 -0.749739  0.024494
2021-01-06 -0.646603  0.124486 -0.646600  0.124484 -0.229360  0.139581
2021-01-07 -0.222928 -0.001366 -0.222933 -0.001365 -0.688375 -0.045969
2021-01-08  0.443405 -0.002725  0.443408 -0.002726  0.343239 -0.103134
2021-01-11 -0.347560  0.089819 -0.347561  0.089819 -0.105893  0.134243
...              ...       ...       ...       ...       ...       ...
2022-12-20 -0.015920  0.174308 -0.015920  0.174308 -0.082174  0.149897
2022-12-21  0.319147  0.156276  0.319147  0.156276  0.283024  0.178954
2022-12-22 -0.144723 -0.235574 -0.144723 -0.235574 -0.144157 -0.131996
2022-12-23  0.150991  0.040384  0.150991  0.040384  0.087870 -0.163446
2022-12-27  0.121847  0.005563  0.121847  0.005563  0.131087  0.090199

                 Low                Open               Volume
                  KO       WMT        KO       WMT         KO       WMT
Date
2021-01-05  0.000000  0.029090 -0.728035  0.316267  -4.624665 -3.886809
2021-01-06 -0.720094  0.071847 -0.138064 -0.207072  12.893597 -3.794475
2021-01-07 -0.268783  0.141557 -0.736905  0.345743   6.361378 -1.301449
2021-01-08  0.128825 -0.031522 -0.023972 -0.100508 -11.685402  3.510122
2021-01-11  0.044093  0.026045  0.234479 -0.120187  -8.598764  1.408630
...              ...       ...       ...       ...        ...       ...
2022-12-20  0.089442  0.073245 -0.003184 -0.012590  -1.194723  2.424521
2022-12-21  0.101733  0.280622  0.079435  0.194962   0.241188 -4.288757
2022-12-22 -0.133630 -0.325665  0.110680  0.062264  -1.484095 -0.961209
2022-12-23  0.174812  0.049260  0.025213 -0.239041  -8.050939 -6.299770
2022-12-27  0.160744  0.127510  0.134977  0.137935   2.491319  1.015117

[499 rows x 12 columns]

In [61]:
retornosa=retornosd*252
retornosa

           Adj Close               Close                High            \
                  KO       WMT        KO       WMT        KO       WMT
Date
2021-01-05 -2.785616 -1.345037 -2.785611 -1.345013 -9.446711  0.308627
2021-01-06 -8.147192  1.568523 -8.147155  1.568494 -2.889933  1.758720
2021-01-07 -2.808894 -0.017207 -2.808953 -0.017200 -8.673530 -0.579213
2021-01-08  5.586903 -0.034336  5.586941 -0.034351  4.324807 -1.299491
2021-01-11 -4.379255  1.131718 -4.379262  1.131719 -1.334254  1.691463
...              ...       ...       ...       ...       ...       ...
2022-12-20 -0.200586  2.196284 -0.200586  2.196284 -1.035393  1.888700
2022-12-21  4.021249  1.969082  4.021249  1.969082  3.566103  2.254821
2022-12-22 -1.823506 -2.968227 -1.823506 -2.968227 -1.816378 -1.663155
2022-12-23  1.902492  0.508840  1.902492  0.508840  1.107168 -2.059421
2022-12-27  1.535268  0.070090  1.535268  0.070090  1.651699  1.136505

                 Low                Open                Volume
                  KO       WMT        KO       WMT          KO        WMT
Date
2021-01-05  0.000000  0.366532 -9.173239  3.984963  -58.270776 -48.973799
2021-01-06 -9.073178  0.905267 -1.739607 -2.609111  162.459325 -47.810386
2021-01-07 -3.386663  1.783616 -9.285006  4.356364   80.153360 -16.398257
2021-01-08  1.623192 -0.397183 -0.302045 -1.266404 -147.236070  44.227536
2021-01-11  0.555570  0.328163  2.954431 -1.514353 -108.344424  17.748734
...              ...       ...       ...       ...         ...        ...
2022-12-20  1.126973  0.922891 -0.040120 -0.158634  -15.053508  30.548959
2022-12-21  1.281833  3.535841  1.000875  2.456518    3.038969 -54.038341
2022-12-22 -1.683741 -4.103382  1.394574  0.784526  -18.699601 -12.111235
2022-12-23  2.202633  0.620679  0.317688 -3.011920 -101.441836 -79.377096
2022-12-27  2.025377  1.606626  1.700706  1.737981   31.390614  12.790471

[499 rows x 12 columns]

B.

In [62]:
volatilidadm=retornosm.std()
volatilidadm

Adj Close  KO     0.219977
           WMT    0.283847
Close      KO     0.221876
           WMT    0.283905
High       KO     0.199552
           WMT    0.245717
Low        KO     0.205548
           WMT    0.261912
Open       KO     0.224010
           WMT    0.274699
Volume     KO     6.360940
           WMT    7.231110
dtype: float64

In [63]:
volatilidadm*12

Adj Close  KO      2.639720
           WMT     3.406163
Close      KO      2.662511
           WMT     3.406861
High       KO      2.394622
           WMT     2.948608
Low        KO      2.466575
           WMT     3.142941
Open       KO      2.688125
           WMT     3.296389
Volume     KO     76.331282
           WMT    86.773319
dtype: float64

C.

In [64]:
retornosd.describe()

        Adj Close                   Close                    High              \
               KO         WMT          KO         WMT          KO         WMT
count  499.000000  499.000000  499.000000  499.000000  499.000000  499.000000
mean     0.000514    0.000025    0.000394   -0.000038    0.000326   -0.000034
std      0.010999    0.014192    0.011094    0.014195    0.009978    0.012286
min     -0.072168   -0.120765   -0.072169   -0.120765   -0.072137   -0.085646
25%     -0.004927   -0.006438   -0.005153   -0.006438   -0.004684   -0.006265
50%      0.001129    0.000501    0.001129    0.000404    0.000000    0.000491
75%      0.006814    0.007757    0.006814    0.007655    0.005558    0.005780
max      0.037942    0.063346    0.037942    0.063346    0.036921    0.053638

              Low                    Open                  Volume
               KO         WMT          KO         WMT          KO         WMT
count  499.000000  499.000000  499.000000  499.000000  499.000000  499.000000
mean     0.000406   -0.000015    0.000328   -0.000004   -0.002510   -0.002333
std      0.010277    0.013096    0.011201    0.013735    0.318047    0.361555
min     -0.064323   -0.114307   -0.070610   -0.090682   -1.331799   -1.069852
25%     -0.004773   -0.005758   -0.005366   -0.006781   -0.174409   -0.216605
50%      0.001179    0.000830    0.000636    0.000000   -0.013880   -0.019601
75%      0.006241    0.006767    0.006750    0.007156    0.172233    0.175728
max      0.033744    0.050688    0.041500    0.053759    1.326459    1.824217

In [65]:
retornosd.kurtosis()

Adj Close  KO      4.402020
           WMT    14.427318
Close      KO      4.426783
           WMT    14.383929
High       KO      6.517005
           WMT    10.921747
Low        KO      4.313293
           WMT    17.995999
Open       KO      3.951003
           WMT     8.542520
Volume     KO      2.570465
           WMT     3.003264
dtype: float64

In [66]:
retornosd.skew()

Adj Close  KO    -0.709275
           WMT   -1.749512
Close      KO    -0.772245
           WMT   -1.740133
High       KO    -0.709371
           WMT   -1.333574
Low        KO    -0.776519
           WMT   -2.252318
Open       KO    -0.571493
           WMT   -1.278680
Volume     KO     0.115177
           WMT    0.732053
dtype: float64

D.

In [71]:
from scipy.stats import norm
x = np.linspace(-0.1,0.1, num=100)
plt.hist(retornosd['WMT'],bins=20,density=True, histtype='step');
plt.plot(x,norm.pdf(x,scale=retornosd['WMT'].std()),'k')
plt.axvline((retornosd['WMT'].mean()), color='r');
plt.xlabel('Retornos');
plt.ylabel('Probabilidad');

KeyError: ignored

In [69]:
from scipy.stats import norm
x = np.linspace(-0.1,0.1, num=100)
plt.hist(retornosd['KO'],bins=20,density=True, histtype='step');
plt.plot(x,norm.pdf(x,scale=retornosd['KO'].std()),'k')
plt.axvline((retornosd['KO'].mean()), color='r');
plt.xlabel('Retornos');
plt.ylabel('Probabilidad');

KeyError: ignored

E.

In [ ]:
retornosd['NVDA'].corr(retornosd['KO'],method="pearson")

In [ ]:
retornosd['NVDA'].corr(retornosd['KO'],method="kendall")

In [ ]:
retornosd['NVDA'].corr(retornosd['KO'],method="spearman")

Punto 2

In [ ]:
activos=['V','JPM','JNJ','DHR','CVS','XOM','TSLA','VZ','TGT','PEP']
fuente='yahoo'
inicio='2017-12-01'
final='2022-12-28'
tabla2=data.DataReader(activos,inicio,final,interval='1Mo')['Adj Close']
tabla2

a.

In [ ]:
retornosp=np.log(tabla2/tabla2.shift()).dropna()
retornosp

In [ ]:
retornosp*12

In [ ]:
volatilidad=retornosp.std()
volatilidad

In [ ]:
volatilidad*12

b.

In [ ]:
Er=retornosp.mean()
ranking=pd.DataFrame(Er)
ranking.index.name='Retorno Esperado'
ranking.sort_values(by=0, ascending=False)

Punto 3

In [ ]:
activos=['^RUT']
fuente='yahoo'
inicio='2011-12-01'
final='2022-12-28'
tabla3=data.DataReader(activos,inicio,final,interval='1Mo')['Adj Close']
tabla3

a.

In [ ]:
retornosr=np.log(tabla3/tabla3.shift()).dropna().loc[:]
r_mensuales=retornosr.std()
r_mensuales

In [ ]:
r_mensuales*12

b.

In [ ]:
activos=['^RUT']
fuente='yahoo'
inicio='2011-12-01'
final='2022-12-28'
tablaprecios=data.DataReader(activos,inicio,final,interval='1Mo')
tablaprecios

In [ ]:
retornoslh = np.log(tablaprecios["High"]/tablaprecios["Low"]).dropna()
sigma1=((1/(4*np.log(2)))*retornoslh**2)**0.5
sigma1.mean()

In [ ]:
(sigma1.mean())*np.sqrt(252)

C.

In [ ]:
retnornosLH = np.log(tablaprecios["High"]/tablaprecios["Low"]).dropna()
retornosCO = np.log(tablaprecios["Close"]/tablaprecios["Open"]).dropna()
sigma2 = (0.5*lnHL**2-(2*np.log(2)-1)*lnCO**2)**0.5
sigma2.mean()

In [ ]:
(sigma2.mean())*np.sqrt(252)

d.

In [ ]:
retornosE = np.log(tabla3/tabla3.shift()).dropna();
Lambda = 0.94
t = (retornosE-1)
t1 = t[::-1] 
k = np.arange(502-1,-1,-1)
k.shape

In [ ]:
alpha = np.power(Lambda,k)
pd.Series(alpha)
alpha.shape
alpha

In [ ]:
EWMA = (alpha[370:502]*retornosE**2)
np.sqrt(EWMA)

In [ ]:
Anual=EWMA.sum()*(1-Lambda)
Anual